m2l_homepage:
    path:     /
    defaults: { _controller: M2LFormationBundle:Formation:index }

m2l_formation:
    path:   /formations
    defaults: { _controller: M2LFormationBundle:Formation:index }

m2l_formation_add:
    path:   /formations/add
    defaults: { _controller: M2LFormationBundle:Formation:add }

m2l_formation_edit:
    path:   /formations/edit/{id}
    defaults: { _controller: M2LFormationBundle:Formation:edit }

m2l_add_my_formation:
    path:   /mes_formations/add/{id}
    defaults: { _controller: M2LFormationBundle:Formation:addMyFormation }

m2l_delete_my_formation:
    path:   /mes_formations/delete/{id}
    defaults: { _controller: M2LFormationBundle:Formation:deleteMyFormation }

m2l_my_formation:
    path:   /mes_formations
    defaults: { _controller: M2LFormationBundle:Formation:listformations }

m2l_formation_view:
    path:   /formations/{id}
    defaults: { _controller: M2LFormationBundle:Formation:view }