M2L\UserBundle\Entity\User:
    properties:
        nom:
            - NotBlank: ~

        password:
            - NotBlank: ~
    
        ddn:
            - NotBlank: ~

        ville:
            - NotBlank: ~

        email:
            - Email: ~